config/routes.rb
require 'sidekiq/web'
require 'api/api'

Gitlab::Application.routes.draw do
  #
  # Search
  #
  get 'search' => "search#show"

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web, at: "/admin/sidekiq", as: :sidekiq
  end

  # Enable Grack support
  mount Grack::Bundle.new({
    git_path:     Gitlab.config.git.bin_path,
    project_root: Gitlab.config.gitlab_shell.repos_path,
    upload_pack:  Gitlab.config.gitlab_shell.upload_pack,
    receive_pack: Gitlab.config.gitlab_shell.receive_pack
  }), at: '/', constraints: lambda { |request| /[-\/\w\.]+\.git\//.match(request.path_info) }

  #
  # Help
  #
  get 'help'                => 'help#index'
  get 'help/api'            => 'help#api'
  get 'help/api/:category'  => 'help#api', as: 'help_api_file'
  get 'help/markdown'       => 'help#markdown'
  get 'help/permissions'    => 'help#permissions'
  get 'help/public_access'  => 'help#public_access'
  get 'help/raketasks'      => 'help#raketasks'
  get 'help/ssh'            => 'help#ssh'
  get 'help/system_hooks'   => 'help#system_hooks'
  get 'help/web_hooks'      => 'help#web_hooks'
  get 'help/workflow'       => 'help#workflow'

  #
  # Global snippets
  #
  resources :snippets do
    member do
      get "raw"
    end
  end
  get "/s/:username" => "snippets#user_index", as: :user_snippets, constraints: { username: /.*/ }

  #
  # Public namespace
  #
  namespace :public do
    resources :projects, only: [:index]
    root to: "projects#index"
  end

  #
  # Attachments serving
  #
  get 'files/:type/:id/:filename' => 'files#download', constraints: { id: /\d+/, type: /[a-z]+/, filename:  /.+/ }

  #
  # Admin Area
  #
  namespace :admin do
    resources :users, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
      member do
        put :team_update
        put :block
        put :unblock
      end
    end

    resources :groups, constraints: { id: /[^\/]+/ } do
      member do
        put :project_update
        put :project_teams_update
        delete :remove_project
      end
    end

    resources :teams, constraints: { id: /[^\/]+/ } do
      scope module: :teams do
        resources :members,   only: [:edit, :update, :destroy, :new, :create]
        resources :projects,  only: [:edit, :update, :destroy, :new, :create], constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end

    resource :logs, only: [:show]
    resource :background_jobs, controller: 'background_jobs', only: [:show]

    resources :projects, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }, only: [:index, :show] do
      scope module: :projects, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
        resources :members, only: [:edit, :update, :destroy]
      end
    end

    root to: "dashboard#index"
  end

  get "errors/githost"

  #
  # Profile Area
  #
  resource :profile, only: [:show, :update] do
    member do
      get :account
      get :history
      get :token
      get :design

      put :update_password
      put :reset_private_token
      put :update_username
    end

    resource :notifications
    resource :password
  end

  resources :keys
  match "/u/:username" => "users#show", as: :user, constraints: { username: /.*/ }



  #
  # Dashboard Area
  #
  resource :dashboard, controller: "dashboard" do
    member do
      get :projects
      get :issues
      get :merge_requests
    end
  end

  #
  # Groups Area
  #
  resources :groups, constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}  do
    member do
      get :issues
      get :merge_requests
      get :search
      get :people
      post :team_members
    end
  end

  #
  # Teams Area
  #
  resources :teams, constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/} do
    member do
      get :issues
      get :merge_requests
    end
    scope module: :teams do
      resources :members,   only: [:index, :new, :create, :edit, :update, :destroy]
      resources :projects,  only: [:index, :new, :create, :edit, :update, :destroy], constraints: { id: /[a-zA-Z.0-9_\-\/]+/ }
    end
  end

  resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: :registrations }

  #
  # Project Area
  #
  resources :projects, constraints: { id: /(?:[a-zA-Z.0-9_\-]+\/)?[a-zA-Z.0-9_\-]+/ }, except: [:new, :create, :index], path: "/" do
    member do
      put :transfer
      post :fork
      get :autocomplete_sources
    end

    resources :blob,    only: [:show], constraints: {id: /.+/}
    resources :raw,    only: [:show], constraints: {id: /.+/}
    resources :tree,    only: [:show], constraints: {id: /.+/, format: /(html|js)/ }
    resources :edit_tree,    only: [:show, :update], constraints: {id: /.+/}, path: 'edit'
    resources :commit,  only: [:show], constraints: {id: /[[:alnum:]]{6,40}/}
    resources :commits, only: [:show], constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}
    resources :compare, only: [:index, :create]
    resources :blame,   only: [:show], constraints: {id: /.+/}
    resources :network,   only: [:show], constraints: {id: /(?:[^.]|\.(?!json$))+/, format: /json/}
    resources :graphs, only: [:show], constraints: {id: /(?:[^.]|\.(?!json$))+/, format: /json/}
    match "/compare/:from...:to" => "compare#show", as: "compare", via: [:get, :post], constraints: {from: /.+/, to: /.+/}

    scope module: :projects do
      resources :snippets do
        member do
          get "raw"
        end
      end
    end

    resources :wikis, only: [:show, :edit, :destroy, :create] do
      collection do
        get :pages
        put ':id' => 'wikis#update'
        get :git_access
      end

      member do
        get "history"
      end
    end

    resource :wall, only: [:show] do
      member do
        get 'notes'
      end
    end

    resource :repository do
      member do
        get "branches"
        get "tags"
        get "stats"
        get "archive"
      end
    end

    resources :services, constraints: { id: /[^\/]+/ }, only: [:index, :edit, :update] do
      member do
        get :test
      end
    end

    resources :deploy_keys do
      member do
        put :enable
        put :disable
      end
    end

    resources :protected_branches, only: [:index, :create, :destroy]

    resources :refs, only: [] do
      collection do
        get "switch"
      end

      member do
        # tree viewer logs
        get "logs_tree", constraints: { id: /[a-zA-Z.\/0-9_\-#%+]+/ }
        get "logs_tree/:path" => "refs#logs_tree",
          as: :logs_file,
          constraints: {
            id:   /[a-zA-Z.0-9\/_\-#%+]+/,
            path: /.*/
          }
      end
    end

    resources :merge_requests, constraints: {id: /\d+/}, except: [:destroy] do
      member do
        get :diffs
        get :automerge
        get :automerge_check
        get :ci_status
      end

      collection do
        get :branch_from
        get :branch_to
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end

    resources :team, controller: 'team_members', only: [:index]
    resources :milestones, except: [:destroy]

    resources :labels, only: [:index] do
      collection do
        post :generate
      end
    end

    resources :issues, except: [:destroy] do
      collection do
        post  :bulk_update
      end
    end

    resources :team_members, except: [:index, :edit] do
      collection do

        # Used for import team
        # from another project
        get :import
        post :apply_import
      end
    end

    scope module: :projects do
      resources :teams, only: [] do
        collection do
          get :available
          post :assign
        end
        member do
          delete :resign
        end
      end
    end

    resources :notes, only: [:index, :create, :destroy] do
      collection do
        post :preview
      end
    end
  end

  root to: "dashboard#show"
end

app/controllers/team_members_controller.rb
class TeamMembersController < ProjectResourceController
  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_admin_project!, except: [:index, :show]

  def index
    @team = @project.users_projects.scoped
    @team = @team.send(params[:type]) if %w(masters developers reporters guests).include?(params[:type])
    @team = @team.sort_by(&:project_access).reverse.group_by(&:project_access)

    @assigned_teams = @project.user_team_project_relationships
  end

  def new
    @user_project_relation = project.users_projects.new
  end

  def create
    users = User.where(id: params[:user_ids].split(','))

    @project.team << [users, params[:project_access]]

    if params[:redirect_to]
      redirect_to params[:redirect_to]
    else
      redirect_to project_team_index_path(@project)
    end
  end

  def update
    @user_project_relation = project.users_projects.find_by_user_id(member)
    @user_project_relation.update_attributes(params[:team_member])

    unless @user_project_relation.valid?
      flash[:alert] = "User should have at least one role"
    end
    redirect_to project_team_index_path(@project)
  end

  def destroy
    @user_project_relation = project.users_projects.find_by_user_id(member)
    @user_project_relation.destroy

    respond_to do |format|
      format.html { redirect_to project_team_index_path(@project) }
      format.js { render nothing: true }
    end
  end

  def apply_import
    giver = Project.find(params[:source_project_id])
    status = @project.team.import(giver)
    notice = status ? "Succesfully imported" : "Import failed"

    redirect_to project_team_index_path(project), notice: notice
  end

  protected

  def member
    @member ||= User.find_by_username(params[:id])
  end
end

app/views/team_members/_assigned_team.html.haml
%li{id: dom_id(team), class: "user_team_row team_#{team.id}"}
  .pull-right
    - if can?(current_user, :admin_team_member, @project)
      = link_to resign_project_team_path(@project, team), method: :delete, confirm: "Are you sure?", class: "btn btn-remove btn-tiny" do
        %i.icon-minus.icon-white

  %strong= link_to team.name, team_path(team), title: team.name, class: "dark"
  %br
  %small.cgray Members: #{team.members.count}
  %small.cgray Max access: #{team_relation.human_max_access}

app/views/team_members/_assigned_teams.html.haml
.ui-box
  %ul.well-list
    - assigned_teams.sort_by(&:team_name).each do |team_relation|
      = render "team_members/assigned_team", team_relation: team_relation, team: team_relation.user_team

app/views/team_members/_form.html.haml
%h3.page_title
  = "New Team member(s)"
%hr
= form_for @user_project_relation, as: :team_member, url: project_team_members_path(@project) do |f|
  -if @user_project_relation.errors.any?
    .alert.alert-error
      %ul
        - @user_project_relation.errors.full_messages.each do |msg|
          %li= msg

  %h6 1. Choose people you want in the team
  .clearfix
    = f.label :user_ids, "People"
    .input
      = users_select_tag(:user_ids, multiple: true)

  %h6 2. Set access level for them
  .clearfix
    = f.label :project_access, "Project Access"
    .input= select_tag :project_access, options_for_select(Project.access_options, @user_project_relation.project_access), class: "project-access-select chosen"

  .actions
    = f.submit 'Add users', class: "btn btn-create"
    = link_to "Cancel", project_team_index_path(@project), class: "btn btn-cancel"

app/views/team_members/_team.html.haml
- can_admin_project = (can? current_user, :admin_project, @project)
- team.each do |access, members|
  - role = Project.access_options.key(access).pluralize
  .ui-box{class: role.downcase}
    %h5.title
      = role
      %span.light (#{members.size})
    %ul.well-list
      - members.sort_by(&:user_name).each do |team_member|
        = render 'team_members/team_member', member: team_member, current_user_can_admin_project: can_admin_project

app/views/team_members/_team_member.html.haml
- user = member.user
- allow_admin = current_user_can_admin_project
%li{id: dom_id(user), class: "team_member_row user_#{user.id}"}
  .row
    .span4
      = link_to user, title: user.name, class: "dark" do
        = image_tag gravatar_icon(user.email, 32), class: "avatar s32"
        %strong= truncate(user.name, lenght: 40)
        %br
        %small.cgray= user.username

    .span4.pull-right
      - if allow_admin
        .left
          = form_for(member, as: :team_member, url: project_team_member_path(@project, member.user)) do |f|
            = f.select :project_access, options_for_select(UsersProject.access_roles, member.project_access), {}, class: "medium project-access-select span2 trigger-submit"
      .pull-right
        - if current_user == user
          %span.label.label-success This is you!
        - if @project.namespace_owner == user
          %span.label.label-info Owner
        - elsif user.blocked?
          %span.label.label-error Blocked
        - elsif allow_admin
          = link_to project_team_member_path(@project, user), confirm: remove_from_project_team_message(@project, user), method: :delete, class: "btn-tiny btn btn-remove", title: 'Remove user from team' do
            %i.icon-minus.icon-white

app/views/team_members/import.html.haml
= render "projects/settings_nav"

%h3.page_title
  = "Import team from another project"
%hr
%p.slead
  Read more about project team import #{link_to "here", '#', class: 'vlink'}.
= form_tag apply_import_project_team_members_path(@project), method: 'post' do
  %p.slead Choose project you want to use as team source:
  .padded
    = label_tag :source_project_id, "Project"
    .input= select_tag(:source_project_id, options_from_collection_for_select(current_user.authorized_projects, :id, :name_with_namespace), prompt: "Select project", class: "chosen xxlarge", required: true)

  .actions
    = submit_tag 'Import', class: "btn btn-save"
    = link_to "Cancel", project_team_index_path(@project), class: "btn btn-cancel"

app/views/team_members/index.html.haml
= render "projects/settings_nav"
%h3.page_title
  Project Members
  (#{@project.users.count})
  %small
    Read more about project permissions
    %strong= link_to "here", help_permissions_path, class: "vlink"

  - if can? current_user, :admin_team_member, @project
    %span.pull-right
      = link_to import_project_team_members_path(@project), class: "btn btn-small grouped", title: "Import team from another project" do
        Import team from another project
      = link_to available_project_teams_path(@project), class: "btn btn-small grouped", title: "Assign project to team of users" do
        Assign project to Team of users
      = link_to new_project_team_member_path(@project), class: "btn btn-primary small grouped", title: "New Team Member" do
        New Team Member

%hr

.clearfix
.row
  .span3
    %ul.nav.nav-pills.nav-stacked
      %li{class: ("active" if !params[:type])}
        = link_to project_team_index_path(type: nil) do
          All
      %li{class: ("active" if params[:type] == 'masters')}
        = link_to project_team_index_path(type: 'masters') do
          Masters
          %span.pull-right= @project.users_projects.masters.count
      %li{class: ("active" if params[:type] == 'developers')}
        = link_to project_team_index_path(type: 'developers') do
          Developers
          %span.pull-right= @project.users_projects.developers.count
      %li{class: ("active" if params[:type] == 'reporters')}
        = link_to project_team_index_path(type: 'reporters') do
          Reporters
          %span.pull-right= @project.users_projects.reporters.count
      %li{class: ("active" if params[:type] == 'guests')}
        = link_to project_team_index_path(type: 'guests') do
          Guests
          %span.pull-right= @project.users_projects.guests.count

    - if @assigned_teams.present?
      %h5
        Assigned teams
        (#{@project.user_teams.count})
      %div
        = render "team_members/assigned_teams", assigned_teams: @assigned_teams

  .span9
    %div.team-table
      = render "team_members/team", team: @team

app/views/team_members/new.html.haml
= render "projects/settings_nav"
= render "team_members/form"

app/views/team_members/update.js.haml
- if @user_project_relation.valid?
  :plain
    $("##{dom_id(@user_project_relation)}").effect("highlight", {color: "#529214"}, 1000);;
- else
  :plain
    $("##{dom_id(@user_project_relation)}").effect("highlight", {color: "#D12F19"}, 1000);;